[package]
name = "wasm-chip8"
version = "0.1.0"
authors = ["nett_hier <lp@netthier.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "^0.3"